import { Poppins } from "next/font/google";
import Nav from "@/components/Nav";
import "./globals.css";
const inter = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-[#FFF7E9] bg-[#161616] h-full w-full min-h-[650px]`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
